[project]
name = "solana-arbitrage"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "asyncio>=4.0.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "requests>=2.32.5",
    "websockets>=15.0.1",
]
